### ISSUE TITLE
`spawn` error when generating output file

### ISSUE THREAD

**Issue by shreyasbharath** [ioquatix/graphviz#7]
Hi,

Thanks for your work on this gem.

I am running into an error on Windows 10 using your gem. Below is my pseudo code -

```
    g = Graphviz::Graph.new

    # Add nodes

    # Add connections

    Graphviz::output(g, path: 'file')
```

Here's the error output -

```
Traceback (most recent call last):
        5: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/process-group-1.1.0/lib/process/group.rb:127:in `block in run'
        4: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/process-group-1.1.0/lib/process/group.rb:135:in `spawn'
        3: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/process-group-1.1.0/lib/process/group.rb:230:in `append!'
        2: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/process-group-1.1.0/lib/process/group.rb:241:in `schedule!'
        1: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/process-group-1.1.0/lib/process/group.rb:45:in `run'
C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/process-group-1.1.0/lib/process/group.rb:45:in `spawn': wrong exec option symbol: pgroup (ArgumentError)
```

As a workaround, I am writing the dot contents manually like so -

`File.write(g.to_dot)`

**Comment by ioquatix** [comment]
Your work around is the best option for now.

Running processes on windows is pretty crazy I have to admit. I'll need to review.
